### ISSUE TITLE
EAD TL element source misses the attribute lastDateTimeVerified in the list of attributes

### ISSUE THREAD

**Issue by karinbredenberg** [SAA-SDT/EAS-TagLibraries#107]
## Creator of issue

1. Karin Bredenberg

## The issue relates to

- [ ] EAC-CPF schema issue
- [ ] EAC-CPF Tag Library issue
- [ ] EAD schema issue
- [X] EAD Tag Library issue
- [ ] Schema issue
- [ ] Tag Library issue
- [ ] Suggestions for all schemas
- [ ] Suggestions for all Tag Libraries
- [ ] Other

## Wanted change/feature

* Text: The list of attributes for the element source misses the attribute lastdatetimeverified which is present in the schema and also in the example for the sourceEntry example.

## Suggested Solution

* Text: Addition of the attribute to the attributes list.

**Comment by alexduryee** [comment]
I checked the TEI, PDF, and HTML for EAD3 and `@lastdatetimeverified` is listed as a valid attribute, and is present in the examples - is it missing from another part of the TL?

**Comment by alexduryee** [comment]
Closing this issue out - loc.gov is hosting an old version of the tag library, which does not include the fixed attributes list for `<source>`.
