### ISSUE TITLE
Wrong example encoding with <citedRange>

### ISSUE THREAD

**Issue by kerstarno** [SAA-SDT/EAS-TagLibraries#108]
## Creator of issue

1. Kerstin Arnold
2. TS-EAS, Working Group on Standards (WGoS) of Archives Portal Europe
3. @kerstarno 
4.

## The issue relates to

- [ ] EAC-CPF schema issue
- [x] EAC-CPF Tag Library issue
- [ ] EAD schema issue
- [ ] EAD Tag Library issue
- [ ] Schema issue
- [ ] Tag Library issue
- [ ] Suggestions for all schemas
- [ ] Suggestions for all Tag Libraries
- [ ] Other

## Reporting a bug

* Text: The example used with `<citedRange>` in the EAC-CPF 2.0 Tag Library includes the element `<citation>` instead of `<reference>` as sub-element of `<source>`.

## Suggested Solution

* Text: Adapt the example by replacing `<citation>` with `<reference>`

## Steps to Reproduce (for bugs)

1. See https://eac.staatsbibliothek-berlin.de/schema/v2/eac.html#elem-citedRange

**Comment by marieelia** [comment]
@ailie-s Just checking to see that this is something you would update, or I can create a pull request with the change, and you approve/merge? For future TL issues, just want to be sure of the workflow.

**Comment by ailie-s** [comment]
@marieelia - I'll update this.

**Comment by ailie-s** [comment]
Corrected - updated Tag Libraries currently in development branch.

**Comment by kerstarno** [comment]
Closing this as it has been resolved.
