### ISSUE TITLE
Example for @linkrole

### ISSUE THREAD

**Issue by SJagodzinski** [SAA-SDT/EAS-TagLibraries#109]
Example values for [`@linkrole`](https://loc.gov/ead/EAD3taglib/EAD3.html#attr-linkrole)

## Creator of issue

1. Silke Jagodzinski
2. TS-EAS: EAC-CPF subgroup
3. silkejagodzinski@gmail.com

## The issue relates to

- [ ] EAC-CPF schema issue
- [ ] EAC-CPF Tag Library issue
- [ ] EAD schema issue
- [x] EAD Tag Library issue
- [ ] Schema issue
- [ ] Tag Library issue
- [ ] Suggestions for all schemas
- [ ] Suggestions for all Tag Libraries
- [ ] Other

## Wanted change/feature

Example value for `@linkrole` as used in Archivportal D resp. its EAD 2002 profile: [xlink:role](https://wiki.deutsche-digitale-bibliothek.de/display/DFD/xlink%3Arole)](https://wiki.deutsche-digitale-bibliothek.de/display/DFD/xlink%3Arole)

## Context

When looking for a good example for EAC-CPF Tag Library for [`@linkRole`](https://github.com/SAA-SDT/eac-cpf-schema/issues/248), I checked EAD(DDB) definition as this attribute is used for dislplay purposes. The values defined for EAD(DDB) are not suitable for EAC-CPF but may be suitable for EAD.

**Comment by SJagodzinski** [comment]
Example encodings from EAD(DDB):

`<archdesc level="collection" type="Findbuch">
 <did>
			<unitid>Bestandssignatur</unitid>
			<repository>
				<corpname role="Staatliche Archive" id="DE-ISIL">Name des Archivs</corpname>
				<address>
					<addressline>Adresse des Archivs + Email</addressline>
				</address>
				<extref xlink:role="url_archive" xlink:href="Link_zur_Website_des_Archivs">Name des
					Archivs</extref>
			</repository>
		</did> [...] `

`<archdesc level="collection" type="Findbuch"> [...] <otherfindaid>
			<extref xlink:role="url_findbuch" xlink:href="Permalink_zum_Online_Findbuch"> Findbuch
				im Angebot des Archivs </extref>
		</otherfindaid> [...]`

`<c level="class" id="Identifier_der_Rubrik"> [...]
					<otherfindaid>
						<extref xlink:role="url_archivalunit"
							xlink:href="Permalink_zur_Anzeige_im_Herkunftssystem"
							>Titelaufnahme im Angebot des Archivs</extref>
					</otherfindaid> [...]`

`<c level="file" id="Identifier_der_Titelaufnahme"> [...] <otherfindaid>
								<extref xlink:role="url_archivalunit"
									xlink:href="Permalink_zur_Anzeige_im_Herkunftssystem"
									>Titelaufnahme im Angebot des Archivs</extref>
							</otherfindaid> [...] <daogrp id="Identifier_des_Digitalisats"> [...] <daoloc xlink:role="image_full"
									xlink:href="Link_zum_Bild (freistehend, nicht in einem Viewer)"/>
								<daoloc xlink:role="externer_viewer"
									xlink:href="Link_zum_Viewer_im_Herkunftssystem"/>
								<daoloc xlink:role="METS" xlink:href="Link_zur_Metsdatei"/>
							</daogrp> [...]`

Source: https://github.com/Deutsche-Digitale-Bibliothek/ddb-metadata-ead/blob/master/ead_ddb/1.2/example/EAD_DDB_Findbuch_optimum_1.2.xml

**Comment by alexduryee** [comment]
I don't see `@linkrole` in this EAD document - just `@xlink:role` - so I'm not quite clear what to add as an example to the tag library.

**Comment by kerstarno** [comment]
Hi Alex, 

yes, apologies, the German Archives Portal currently uses EAD 2002, so Silke's examples are based on that. I've updated them to be EAD3 compliant:

```
<archdesc level="collection" localtype="Findbuch">
        <did>
            <unitid>Bestandssignatur</unitid>
            <repository>
                <corpname relator="Staatliche Archive" id="DE-ISIL">
                    <part>Name des Archivs
                        <ref linkrole="url_archive" href="Link_zur_Website_des_Archivs">Homepage des Archivs</ref>
                    </part>
                </corpname>
                <address>
                    <addressline>Adresse des Archivs + Email</addressline>
                </address>
            </repository>
        </did>
</archdesc>
```
```
<archdesc level="collection" localtype="Findbuch">
            <did>
                <unittitle/>
            </did>
            <otherfindaid>
                <p>
                    <ref linkrole="url_findbuch" href="Permalink_zum_Online_Findbuch">Findbuch im Angebot des Archivs</ref>
                </p>
            </otherfindaid>
            <dsc>
                <c level="class" id="Identifier_der_Rubrik">
                    <did>
                        <unittitle/>
                    </did>
                    <otherfindaid>
                        <p>
                            <ref linkrole="url_archivalunit" href="Permalink_zur_Anzeige_im_Herkunftssystem">Titelaufnahme im Angebot des Archivs</ref>
                        </p>
                    </otherfindaid>
                    <c level="file" id="Identifier_der_Titelaufnahme">
                        <did>
                            <unittitle/>
                        </did>
                        <otherfindaid>
                            <p>
                                <ref linkrole="url_archivalunit" href="Permalink_zur_Anzeige_im_Herkunftssystem">Titelaufnahme im Angebot des Archivs</ref>
                            </p>
                        </otherfindaid>
                        <c>
                            <did>
                                <daoset id="Identifier_des_Digitalisats">
                                    <dao daotype="derived" linkrole="image_full" href="Link_zum_Bild (freistehend, nicht in einem Viewer)"/>
                                    <dao daotype="otherdaotype" otherdaotype="viewer" linkrole="externer_viewer" href="Link_zum_Viewer_im_Herkunftssystem"/>
                                    <dao daotype="otherdaotype" otherdaotype="METS" linkrole="METS" href="Link_zur_Metsdatei"/>
                                </daoset>
                            </did>
                        </c>
                    </c>
                </c>
            </dsc>
</archdesc>
```
For inclusion on the TL, I'd suggest to use the example of the first `<archdesc>` element and the example with `<daoset>`.

**Comment by alexduryee** [comment]
@kerstarno Thanks!  I'm not entirely sure that these examples will work, though - `linkrole` and `href` should be anyURI, but look like they're placeholder strings in these examples (e.g. `Permalink_zur_Anzeige_im_Herkunftssystem`).  @SJagodzinski - are these template values, or are these valid URIs for this finding aid?

**Comment by SJagodzinski** [comment]
@alexduryee : values of `@linkrole` are used as strings as there is no URI available. Values for `@href` are placeholders for valid URIs for a finding aid. The xml snippet here is no real world finding aid, but an extended example file, using elements content and attribute values as description of the element or attribute. Do you need a real world example?

**Comment by kerstarno** [comment]
@SJagodzinski - if you would have a real world example e.g. prepared from the GStA for Archivportal-D that uses (some of) these instances of `@linkrole` and `@href`, that would be great. Thank you very much in advance!

**Comment by SJagodzinski** [comment]
Example 1:

```
<archdesc level="collection" localtype="Findbuch">
    <did>
        <unitid>BPH, Rep. 61</unitid>
        <repository>
            <corpname relator="Staatliche Archive" id="DE-2884">
                <part>Name des Archivs
                    <ref linkrole="url_archive" href="https://gsta.preussischer-kulturbesitz.de/">Geheimes Staatsarchiv Preußischer Kulturbesitz</ref>
                </part>
            </corpname>
        </repository>
    </did>
</archdesc>
```

Example 2:
```
<archdesc level="collection" localtype="Findbuch">
    <dsc>
        <c id="GStA_bph_rep_113_3_5" level="class">
            <did>
                <unittitle>03.05 Reisen, Aufenthalte</unittitle>
            </did>
            <otherfindaid>
                <p>
                    <ref linkrole="url_archivalunit" href="http://archivdatenbank.gsta.spk-berlin.de/midosasearch-gsta/MidosaSEARCH/bph_rep_113/index.htm?kid=GStA_bph_rep_113_3_5"/>
                </p>
            </otherfindaid>
            <c id="GStA_bph_rep_113_BPH_Rep_113_Nr_1071" level="file">
                <did>
                    <unittitle>Übersichten zu den Reisen Kaiser Wilhelms II. mit chronologischer Übersicht und Hinweis auf die dazugehörigen Akten</unittitle>
                </did>
                <otherfindaid>
                    <p>
                        <ref linkrole="url_archivalunit" href="http://archivdatenbank.gsta.spk-berlin.de/midosasearch-gsta/MidosaSEARCH/bph_rep_113/index.htm?kid=GStA_bph_rep_113_3_5&amp;uid=GStA_bph_rep_113_BPH_Rep_113_Nr_1071"/>
                    </p>
                </otherfindaid>
                <c>
                    <did>
                        <daoset id="Identifier_des_Digitalisats">
                            <dao daotype="image/jpeg" linkrole="image_full" href="https://archivdatenbank.gsta.spk-berlin.de/midosasearch-gsta/MidosaSEARCH/bph_rep_113/mets/BPH,%20Rep.%20113,%20Nr.%201071/DEFAULT/BPH_Rep_113_Nr_1071_0001.jpg"/>
                        </daoset>
                    </did>
                    
                </c>
            </c>
        </c>
    </dsc>
</archdesc>
```

**Comment by SJagodzinski** [comment]
Does that work?

**Comment by alexduryee** [comment]
@SJagodzinski I don't think these examples work, unfortunately - `linkrole` itself has to be a URI.  Working through these examples and the `linkrole` definition, though, I'm increasingly unclear _why_ `linkrole` is defined as `xs:anyURI` - the examples you've provided seem like they use the field as described (defining what a `href` points to), but the schema and data definitions don't agree.

I'll ask about this at the next schema team meeting, since as far as I can tell, even the existing `linkrole="application/pdf"` example in the tag library is incorrect!

**Comment by fordmadox** [comment]
Just to follow up after the Schema Team discussion, we have decided to keep the anyURI datatype for this attribute as is for now.  Instead, we will alter the example to use an absolute URI to make the tag library easier to understand.  So,

`linkrole="https://www.iana.org/assignments/media-types/application/pdf"`

We will still do a review of all data types as part of the EAD4 redesign, though!

**Comment by fordmadox** [comment]
That said, please note that values such as "application/pdf" are also perfectly valid URIs.  For an explanation of the XSD anyURI datatype, see http://www.datypic.com/sc/xsd/t-xsd_anyURI.html, specifically:

> URIs are used to identify resources, and they may be absolute or relative. Absolute URIs provide the entire context for locating the resources, such as http://datypic.com/prod.html. Relative URIs are specified as the difference from a base URI, such as ../prod.html. It is also possible to specify a fragment identifier, using the # character, such as ../prod.html#shirt.

> The three previous examples happen to be HTTP URLs (Uniform Resource Locators), but URIs also encompass URLs of other schemes (e.g., FTP, gopher, telnet), as well as URNs (Uniform Resource Names). **URIs are not required to be dereferencable**; that is, it is not necessary for there to be a web page at http://datypic.com/prod.html in order for this to be a valid URI.

**Comment by kerstarno** [comment]
Closing this as it has been resolved.
