### ISSUE TITLE
Suggestion to adapt the explanation of the value "updated" for @maintenanceEventType

### ISSUE THREAD

**Issue by kerstarno** [SAA-SDT/EAS-TagLibraries#110]
## Creator of issue

1. Kerstin Arnold
2. @kerstarno 
3. Archives Portal Europe Foundation, Working Group on Standards
4.

## The issue relates to

- [ ] EAC-CPF schema issue
- [x] EAC-CPF Tag Library issue
- [ ] EAD schema issue
- [ ] EAD Tag Library issue
- [ ] Schema issue
- [ ] Tag Library issue
- [ ] Suggestions for all schemas
- [ ] Suggestions for all Tag Libraries
- [ ] Other

## Reporting a bug

* Text: It would seem that the explanation used for the value "updated" for `@maintenanceEventType` in the EAC-CPF 2.0 Tag Library is a simple copy from the EAD3 Tag Library's description of `<eventType>` as it speaks of "significant changes to the materials being described".

## Suggested Solution

* Text:  I'd suggest changing this to "significant changes to the entity's description"

## Steps to Reproduce (for bugs)

1. See https://eac.staatsbibliothek-berlin.de/schema/v2/eac.html#attr-maintenanceEventReference

**Comment by marieelia** [comment]
@kerstarno agreed. @ailie-s maybe I can chat to you about how we make updates, as I haven't done that--and I don't want to accidentally mess something up.

**Comment by ailie-s** [comment]
Corrected - updated Tag Libraries currently in development branch.

**Comment by kerstarno** [comment]
Closing this as it has been resolved.
