### ISSUE TITLE
Typo in the summary of `@targetType`

### ISSUE THREAD

**Issue by kerstarno** [SAA-SDT/EAS-TagLibraries#111]
## Creator of issue

1. Kerstin Arnold
2. @kerstarno 
3. Archives Portal Europe Foundation, Working Group on Standards
4.

## The issue relates to

- [ ] EAC-CPF schema issue
- [x] EAC-CPF Tag Library issue
- [ ] EAD schema issue
- [ ] EAD Tag Library issue
- [ ] Schema issue
- [ ] Tag Library issue
- [ ] Suggestions for all schemas
- [ ] Suggestions for all Tag Libraries
- [ ] Other

## Reporting a bug

* Text: The summary of `@targetType` is missing a "d" in the word "relate**d**".

## Suggested Solution

* Text: Correct the text to say "...relate**d** to the CPF entity being described."

## Steps to Reproduce (for bugs)

1. See https://eac.staatsbibliothek-berlin.de/schema/v2/eac.html#attr-targetType

**Comment by marieelia** [comment]
@ailie-s This one is a quick fix--are you able to update?

**Comment by ailie-s** [comment]
Corrected - updated Tag Libraries currently in development branch.
