### ISSUE TITLE
Values mentioned in Tag Library for @parallel are wrong

### ISSUE THREAD

**Issue by kerstarno** [SAA-SDT/EAS-TagLibraries#113]
## Creator of issue

1. Kerstin Arnold
2. @kerstarno 
3. TS-EAS
4.

## The issue relates to

- [ ] EAC-CPF schema issue
- [ ] EAC-CPF Tag Library issue
- [ ] EAD schema issue
- [x] EAD Tag Library issue
- [ ] Schema issue
- [ ] Tag Library issue
- [ ] Suggestions for all schemas
- [ ] Suggestions for all Tag Libraries
- [ ] Other

## Reporting a bug

* Text: The values listed in the Tag Library for the attribute `@parallel` currently say "part" and "whole", but they should say "false" and "true" as the attribute is defined as boolean. I checked that this is indeed an issue that exists in the TEI XML right now and is not an issue of getting the HTML/PDF versions updated on the LoC website.

## Suggested Solution

* Text: Correct the values to say "false" and "true".

**Comment by fordmadox** [comment]
Oh yeah, it looks like the values for `@coverage` got added here by mistake.  

As an aside:  it would be great to break up the TEI file so that we can reference the line numbers more easily within GitHub (which would not only help with maintenance, but also with the review process).  As it stands now, though, the file is too large for GitHub to render online.  

For reference:  lines 2183-2185 should be:

```
               <div type="values">
                  <p>false, true</p>
               </div>
```

**Comment by fordmadox** [comment]
Good to note that there's no issue here, https://eadiva.com/physdescset/, though 😄  

Maybe instead of breaking up the TEI file, it would be best just to derive the documentation from the schema for EAD4, rather than developing those separately.

**Comment by alexduryee** [comment]
@fordmadox the TEI for EAC used to be split up into one per element/attribute, but I don't recall why they were merged back together - ironically, it may have been for ease of maintenance at the time.  Now that building the documents is automated, it may be worth revisiting splitting the files out again.

**Comment by kerstarno** [comment]
Closing this as it has been resolved.
