### ISSUE TITLE
Clarifying the use of EAC's entityId

### ISSUE THREAD

**Issue by alexduryee** [SAA-SDT/EAS-TagLibraries#12]
## Creator of issue

1. Alex Duryee
2. NYPL
3. alexanderduryee@nypl.org

## The issue relates to

- [ ] EAC-CPF schema issue
- [x] EAC-CPF Tag Library issue
- [ ] EAD schema issue
- [ ] EAD Tag Library issue
- [ ] Schema issue
- [ ] Tag Library issue
- [ ] Suggestions for all schemas
- [ ] Suggestions for all Tag Libraries
- [ ] Other

## Wanted change/feature

* Text:  There seems to be confusion as to how `entityId` ought to be used, based on the description and example in the Tag Library.  It isn't clear if `entityId` is for authority identifiers ("assigned by an authoritative agency" seems to suggest this), real-world identifiers ("identifier associated with the CPF entity"), or something else entirely.  The provided example is unclear as to the source/meaning of the element value.

## Suggested Solution

* Text:  Provide more descriptive language regarding values for `entityId`; for example, the MARC URI proposal (https://www.loc.gov/marc/mac/2017/2017-08.html) does a good job of defining real-world identifiers vs. record identifiers.

**Comment by kerstarno** [comment]
I've closed this issue as the element has been renamed to `<identityId>` as part of the revision towards EAC-CPF 2.0 and the description has been updated accordingly.
