### ISSUE TITLE
Examples were the element term is used with attributes

### ISSUE THREAD

**Issue by karinbredenberg** [SAA-SDT/EAS-TagLibraries#121]
## Creator of issue

1. Karin Bredenberg
2. TS EAS
3.
4.

## The issue relates to

- [ ] EAC-CPF schema issue
- [X] EAC-CPF Tag Library issue
- [ ] EAD schema issue
- [ ] EAD Tag Library issue
- [ ] Schema issue
- [ ] Tag Library issue
- [ ] Suggestions for all schemas
- [ ] Suggestions for all Tag Libraries
- [ ] Other

## Wanted change/feature

* Text: Examples where the element `<term`> is used include attributes not possible to use in the element `<term>`. Connected to the decisions made in [https://github.com/SAA-SDT/eac-cpf-schema/issues/110](https://github.com/SAA-SDT/eac-cpf-schema/issues/110) . In most cases the attributes needs to be moved to the parent in some cases the wrong attribute name is used. 
* Examples needing updates are found in these descriptions:
* https://eac.staatsbibliothek-berlin.de/schema/v2/eac.html#attr-vocabularySource
* https://eac.staatsbibliothek-berlin.de/schema/v2/eac.html#elem-description
* https://eac.staatsbibliothek-berlin.de/schema/v2/eac.html#elem-descriptiveNote
* https://eac.staatsbibliothek-berlin.de/schema/v2/eac.html#elem-localDescription
* https://eac.staatsbibliothek-berlin.de/schema/v2/eac.html#elem-localDescriptions
* https://eac.staatsbibliothek-berlin.de/schema/v2/eac.html#elem-term

## Suggested Solution

* Text: All examples where the element term is used needs to be checked and updated.

## Context

* Text: The examples can be misleading.

**Comment by marieelia** [comment]
@ailie-s Let me know if this is easy enough to update or if I can help. I've never updated the TL in GH, so I don't want to make a mistake.

**Comment by ailie-s** [comment]
I'm happy to make these changes - I'll let you know when it's done.

**Comment by ailie-s** [comment]
I have corrected the examples where term has incorrect attributes (either moving them to the parent element, or in the case of scriptCode, changing it to scriptOfElement).

**Comment by kerstarno** [comment]
Closing this as it has been resolved.
