### ISSUE TITLE
<agent> description in TL needs the 'May contain' section updated, as well as new examples (both still reflect EAD3)

### ISSUE THREAD

**Issue by fordmadox** [SAA-SDT/EAS-TagLibraries#153]
See https://github.com/SAA-SDT/EAS-TagLibraries/blob/65a8eba6d6147288f0285b97d076e49dd4992e0e/tei/ead3/en/elem-agent.xml#L13

## Creator of issue

1.
2.
3.
4.

## The issue relates to

- [ ] EAC-CPF schema issue
- [ ] EAC-CPF Tag Library issue
- [ ] EAD schema issue
- [ ] EAD Tag Library issue
- [ ] Schema issue
- [x ] Tag Library issue
- [ ] Suggestions for all schemas
- [ ] Suggestions for all Tag Libraries
- [ ] Other

## Wanted change/feature

* Text: 

## Reporting a bug

* Text:

## Suggested Solution

* Text: 

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Context

* Text: 

## Your Environment can be a clue to a bug

* Version used:
* Environment name and version (e.g. Chrome 39, node.js 5.4):
* Operating System and version (desktop or mobile):

**Comment by fordmadox** [comment]
Also note that it lists 'agentType' as an attribute, but in the schema it's an element still.

**Comment by kerstarno** [comment]
This is looking at the wrong file. `<agent >` for the EAD 4.0 draft TL is in the shared folder here: https://github.com/SAA-SDT/EAS-TagLibraries/blob/ead4/tei/shared/en/elem-agent.xml

**Comment by fordmadox** [comment]
My mistake!  I had a draft version of the EAD4 PDF file open earlier, before switching to the XSD schema for review.

**Comment by fordmadox** [comment]
The examples still need updating, e.g.  `<agent agentType="human"/>`, but I think that goes for many of the entries at this time.
