### ISSUE TITLE
EAD3 examples review and cleanup - here: breaks in overlong "words"

### ISSUE THREAD

**Issue by alexduryee** [SAA-SDT/EAS-TagLibraries#20]
## Creator of issue

1. Alex Duryee
2. NYPL
3. alexanderduryee@nypl.org

## The issue relates to

- [ ] EAC-CPF schema issue
- [ ] EAC-CPF Tag Library issue
- [ ] EAD schema issue
- [X] EAD Tag Library issue
- [ ] Schema issue
- [ ] Tag Library issue
- [ ] Suggestions for all schemas
- [ ] Suggestions for all Tag Libraries
- [ ] Other

## Wanted change/feature

* Text: The initial text has been adapted to the new breakdown of this issue. The current issue will only deal with those examples, which need breaks in some overlong "words" between spaces, as they currently are spilling into the margin. These are:
- c01
- dsc (maybe also shorten generally)
- languagedeclaration (wow!)
- localcontrol (wow!)

**Comment by karinbredenberg** [comment]
Add in the EAD team?

**Comment by kerstarno** [comment]
At their meeting on 23 September 2019, TS-EAS EAD team decided that this issue be split up into separate ones, which can more easily be assigned to members of the team to take care of the updates of examples. 

It also was decided, that - when working on examples - team members should use files that they would have at their disposal in the context of their work places to avoid made-up examples. Suggestions for examples are to be posted here on GitHub for transparency.

**Comment by kerstarno** [comment]
Closing this issue as it was split into separate issues back in 2019, which all have been completed.
