### ISSUE TITLE
EAC-CPF Examples Cleanup

### ISSUE THREAD

**Issue by alexduryee** [SAA-SDT/EAS-TagLibraries#21]
## Creator of issue

1. Alexander Duryee
2. NYPL

## The issue relates to

- [ ] EAC-CPF schema issue
- [X] EAC-CPF Tag Library issue
- [ ] EAD schema issue
- [ ] EAD Tag Library issue
- [ ] Schema issue
- [ ] Tag Library issue
- [ ] Suggestions for all schemas
- [ ] Suggestions for all Tag Libraries
- [ ] Other

## Reporting a bug

* Text:  Some EAC-CPF elements have examples which are are overlong for their FOP areas, so they spill into the margins/off the pages.  The problem lines should be broken up via spaces/line breaks.

The elements with the problem example texts are:
- control
- eventDateTime
- eventDescription
- eventType
- localDescription
- localDescriptions
- maintenanceEvent
- maintenanceHistory
- resourceRelations (minor spillage)
- term

**Comment by kerstarno** [comment]
Closing this issue as it refers to the EAC-CPF TL, which has now been superseded by the EAC-CPF 2.0 TL.
