### ISSUE TITLE
Just a note that the TL doesn't mention the eac-cpf-grp element.  Should it?  Is that an official EAC feature? 

### ISSUE THREAD

**Issue by fordmadox** [SAA-SDT/EAS-TagLibraries#22]
## The issue relates to

- [ ] EAC-CPF schema issue
- [x] EAC-CPF Tag Library issue
- [ ] EAD schema issue
- [ ] EAD Tag Library issue
- [ ] Schema issue
- [ ] Tag Library issue
- [ ] Suggestions for all schemas
- [ ] Suggestions for all Tag Libraries
- [ ] Other

**Comment by karinbredenberg** [comment]
Nope it isnt. All three files for grouping can be removed.

**Comment by alexduryee** [comment]
Closing issue, since groups are not supported.
