### ISSUE TITLE
Tag Library, Version EN HTML page title error

### ISSUE THREAD

**Issue by ailie-s** [SAA-SDT/EAS-TagLibraries#25]
## Creator of issue

1. Ailie Smith
2. The University of Melbourne
3. ailie.smith@unimelb.edu.au
4.

## The issue relates to

- [ ] EAC-CPF schema issue
- [x] EAC-CPF Tag Library issue
- [ ] EAD schema issue
- [ ] EAD Tag Library issue
- [ ] Schema issue
- [ ] Tag Library issue
- [ ] Suggestions for all schemas
- [ ] Suggestions for all Tag Libraries
- [ ] Other

## Wanted change/feature

* Text: 

## Reporting a bug

* Text: The title in the metadata for the EAC-CPF Tag Library (English HTML version) is currently 
`  <title>EAD Tag Library</title>` rather than `<title>EAC-CPF Tag Library</title>`. This leads to tabs in web browsers, for example, being labelled with the incorrect schema.

## Suggested Solution

* Text: 

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Context

* Text: 

## Your Environment can be a clue to a bug

* Version used: [https://eac.staatsbibliothek-berlin.de/schema/taglibrary/cpfTagLibrary2018_EN.html](url)
* Environment name and version (e.g. Chrome 39, node.js 5.4):
* Operating System and version (desktop or mobile):

**Comment by fordmadox** [comment]
@ailie-s :  i was able to transfer this issue here so no need to re-post it.  i'll try to find out where this is happening in the transformation process (or wherever) and add a comment to indicate why i moved it over to the tag library repository.

**Comment by fordmadox** [comment]
Looks like this is being defined here:  https://github.com/SAA-SDT/EAS-TagLibraries/blob/master/transformations/tagLibrary2html.xsl#L36

**Comment by alexduryee** [comment]
Thanks - closed in #30.
