### ISSUE TITLE
Typo in the English definition for "source" 

### ISSUE THREAD

**Issue by fordmadox** [SAA-SDT/EAS-TagLibraries#31]
## Creator of issue

1.  Mark Custer
2.
3.
4.

## The issue relates to

- [ ] EAC-CPF schema issue
- [x] EAC-CPF Tag Library issue
- [ ] EAD schema issue
- [ ] EAD Tag Library issue
- [ ] Schema issue
- [ ] Tag Library issue
- [ ] Suggestions for all schemas
- [ ] Suggestions for all Tag Libraries
- [ ] Other

## Wanted change/feature

* Text:  

## Reporting a bug

* Text: Typo of "establishement" at https://github.com/SAA-SDT/EAS-TagLibraries/blob/master/tei/EAC-CPF-eng/elem-source.xml#L13   

## Suggested Solution

* Text: 

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Context

* Text: 

## Your Environment can be a clue to a bug

* Version used:
* Environment name and version (e.g. Chrome 39, node.js 5.4):
* Operating System and version (desktop or mobile):

**Comment by kerstarno** [comment]
Closing this issue as it referred to the EAC-CPF TL, which has now been superseded by the EAC-CPF 2.0 TL.
