### ISSUE TITLE
Typo in the English definition of "sources" 

### ISSUE THREAD

**Issue by fordmadox** [SAA-SDT/EAS-TagLibraries#32]
## Creator of issue

1. Mark Custer

## The issue relates to

- [ ] EAC-CPF schema issue
- [x] EAC-CPF Tag Library issue
- [ ] EAD schema issue
- [ ] EAD Tag Library issue
- [ ] Schema issue
- [ ] Tag Library issue
- [ ] Suggestions for all schemas
- [ ] Suggestions for all Tag Libraries
- [ ] Other

## Wanted change/feature

* Text: 

## Reporting a bug

* Text: See https://github.com/SAA-SDT/EAS-TagLibraries/blob/master/tei/EAC-CPF-eng/elem-sources.xml#L13.  Maybe that sentence is intended to be "to record *all* of the sources"?  But, the definition could be updated, and this might be an opportunity to rewrite both the EAD3 and EAC definitions.

## Suggested Solution

* Text: 

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Context

* Text: 

## Your Environment can be a clue to a bug

* Version used:
* Environment name and version (e.g. Chrome 39, node.js 5.4):
* Operating System and version (desktop or mobile):

**Comment by kerstarno** [comment]
Closing this issue as it referred to the EAC-CPF TL, which has now been superseded by the EAC-CPF 2.0 TL.
