### ISSUE TITLE
Use EAD3 for EAC-CPF examples

### ISSUE THREAD

**Issue by alexduryee** [SAA-SDT/EAS-TagLibraries#33]
## Creator of issue

1. Alexander Duryee
2. NYPL

## The issue relates to

- [ ] EAC-CPF schema issue
- [x] EAC-CPF Tag Library issue
- [ ] EAD schema issue
- [ ] EAD Tag Library issue
- [ ] Schema issue
- [ ] Tag Library issue
- [ ] Suggestions for all schemas
- [x] Suggestions for all Tag Libraries
- [ ] Other

## Wanted change/feature

* Text: The EAC-CPF tag library uses EAD2002 for its examples (e.g. in `resourceRelation`).  These examples should be updated to use EAD3, in part to align the tag library with the latest standard, and in part to match the namespace used by the EAD3 tag library.

**Comment by alexduryee** [comment]
Leaving this open, since eventually EAC-CPF ought to use EAD3 in its examples - but that can wait until the schema revision.

**Comment by kerstarno** [comment]
Closing this issue as it referred to the EAC-CPF TL, which has now been superseded by the EAC-CPF 2.0 TL.
