### ISSUE TITLE
Remove separate EAC element/attribute files

### ISSUE THREAD

**Issue by alexduryee** [SAA-SDT/EAS-TagLibraries#35]
EAC-CPF's tag library is currently managed by one top-level file and multiple attr/elem files, which are then combined via `CreateOneFile.xsl`.  These should be combined into one single document, _a la_ EAD3, for ease of management.

## Creator of issue

1. Alexander Duryee / Karin Bredenberg
2. NYPL / SNA

## The issue relates to

- [ ] EAC-CPF schema issue
- [x] EAC-CPF Tag Library issue
- [ ] EAD schema issue
- [ ] EAD Tag Library issue
- [ ] Schema issue
- [ ] Tag Library issue
- [ ] Suggestions for all schemas
- [ ] Suggestions for all Tag Libraries
- [ ] Other

## Wanted change/feature

* Text: Replace the many EAC-CPF tag library files with one.  This also involves updating the templates in `templates/` to reflect the one large document.  The TEI schema(s) also need to be updated in accordance with this change.

**Comment by kerstarno** [comment]
Closing this issue as won't do seeing that we have just undone this again and split the TL into separate TEI XML files per attribute and element.
