### ISSUE TITLE
EAD3 examples review and cleanup - here: <filedesc> section

### ISSUE THREAD

**Issue by kerstarno** [SAA-SDT/EAS-TagLibraries#37]
## Creator of issue

1. Kerstin Arnold
2. TS-EAS EAD team lead
3. @kerstarno

## The issue relates to

- [ ] EAC-CPF schema issue
- [ ] EAC-CPF Tag Library issue
- [ ] EAD schema issue
- [X] EAD Tag Library issue
- [ ] Schema issue
- [ ] Tag Library issue
- [ ] Suggestions for all schemas
- [ ] Suggestions for all Tag Libraries
- [ ] Other

## Wanted change/feature

* Text: Some EAD3 TL elements are missing examples. This issue has been created from #20, where this was initially reported. The current issue deals with the following elements:
- edition
- editionstmt
- publicationstmt
- seriesstmt
- subtitle

**Comment by noahgh221** [comment]
@kerstarno , Here are suggested examples for the following elements: edition, editionstmt, publicationstmt, seriesstmt, subtitle. Some are new examples and some are repurposed from examples elsewhere in the EAD3 and EAD2002 Tag Libraries:

**Example for both `<edition>` and `<editionstmt>`** (repurposed from existing `<filedesc>` example):

```
<filedesc>
    <titlestmt>
        <titleproper>Register of the Emily Higby Collection</titleproper>
    </titlestmt>
    <editionstmt>
        <edition>2nd ed.</edition>
        <p>This edition reflects substantial additions to the collection in 1994.</p>
    </editionstmt>
</filedesc>
```

**Example for `<publicationstmt>`**:
```
<filedesc>
    <titlestmt>
        <titleproper>Guide to the Edward Raymond Zane Letters, 1960</titleproper>
        <author>Noah Huffman</author>
    </titlestmt>
    <publicationstmt>
        <publisher>David M. Rubenstein Rare Book and Manuscript Library</publisher>
        <address>
            <addressline>411 Chapel Drive</addressline>
            <addressline>Duke University</addressline>
            <addressline>Durham 27708</addressline>
        </address>
        <date>February 2016</date>
        <num>RL.11119</num>  
    </publicationstmt>
</filedesc>
```

**Example for `<seriesstmt>`**:
```
<filedesc>
    <titlestmt>
        <titleproper>Guide to the Lucretia Mott Papers, 1848-1887 and undated</titleproper>
        <author>Alice Poffinberger</author>
    </titlestmt>
    <publicationstmt>
        <publisher>David M. Rubenstein Rare Book and Manuscript Library</publisher>
    </publicationstmt>
    <seriesstmt>
        <p>The Lisa Unger Baskin Collection</p>
    </seriesstmt>
</filedesc>
```

**Example for `<subtitle>`** (repurposed from EAD2002 example):
```
<filedesc>
    <titlestmt>
        <titleproper>Tom Stoppard</titleproper> 
        <subtitle>An Inventory of His Papers at the Harry Ransom Humanities Research Center</subtitle>
        <author>Finding aid written by Katherine Mosley</author>
    </titlestmt>
    <publicationstmt>
        <publisher>The University of Texas at Austin, Harry Ransom Humanities Research Center</publisher>
        <date>2000</date>
    </publicationstmt>
</filedesc>
```

**Comment by kerstarno** [comment]
During their meeting on 28 October, EAD team of TS-EAS confirmed the above examples for inclusion into the EAD3 tag library.
