### ISSUE TITLE
EAD3 examples review and cleanup - here: sub-elements of <maintenanceevent> 

### ISSUE THREAD

**Issue by kerstarno** [SAA-SDT/EAS-TagLibraries#38]
## Creator of issue

1. Kerstin Arnold
2. TS-EAS EAD team lead
3. @kerstarno

## The issue relates to

- [ ] EAC-CPF schema issue
- [ ] EAC-CPF Tag Library issue
- [ ] EAD schema issue
- [X] EAD Tag Library issue
- [ ] Schema issue
- [ ] Tag Library issue
- [ ] Suggestions for all schemas
- [ ] Suggestions for all Tag Libraries
- [ ] Other

## Wanted change/feature

* Text: Some EAD3 TL elements are missing examples. This issue has been created from #20, where this was initially reported. The current issue deals with the following elements:
- agent
- agenttype
- eventdescription
- eventtype

**Comment by SJagodzinski** [comment]
1. `<agent>`: I have no real life examples available, but reuse of `<maintenanceevent>` examples might be useful:
`<agent>Michael Rush</agent>`
`<agent>Beinecke Library Edix/Wordix macros</agent>`
`<agent>brbl-migrate-01.xsl</agent>`
`<agent>v1to02.xsl</agent>`
`<agent>yale.addEadidUrl.xsl</agent>`
`<agent>EAD2002_to_EAD3.xsl</agent>`
`<agent>Lisa Bolkonskaya</agent>`

1. `<agenttype>`:  
`<agenttype value="human"/>`
`<agenttype value="machine">EAD2002ToEAD3dtd.xsl</agenttype>`

1.  `<eventdescription>`: 
`<eventdescription lang="ger">Findmittel erstellt.</eventdescription>`
`<eventdescription lang="eng">Finding aid created.</eventdescription>`
 `<eventdescription>EAD migration</eventdescription>`
`<eventdescription>Encoded in EAD 1.0.</eventdescription>`
`<eventdescription>converted for compliance with Yale EAD Best Practice Guidelines </eventdescription>`
`<eventdescription>PUBLIC "-//Yale University::Beinecke Rare Book and Manuscript Library//TEXT (US::CtYBR::::[ABRAHAM HAYWARD COLLECTION ])//EN" "hayward.xml" converted from EAD 1.0 to 2002 by v1to02.xsl (sy2003-10-15).</eventdescription>`
`<eventdescription>Transformed with yale.addEadidUrl.xsl. Adds @url with handle for finding aid. Overwrites @url if already present.</eventdescription>`
`<eventdescription>Conversion from EAD 2002 finding aid using XSL transformation.</eventdescription>`
`<eventdescription>Conversion from EAD 2002 revised. Conventions and local control added..</eventdescription>`
`<eventdescription>Minor revisions. Added sources.</eventdescription>`

1.  `<eventtype>`: 
`<eventtype lang="ger" value="created">Erstellt</eventtype>`
`<eventtype value="derived"/>`

**Comment by kerstarno** [comment]
During their meeting on 28 October, EAD team of TS-EAS confirmed the above examples for inclusion into the EAD3 tag library. While doing this, the examples will be integrated into a wrapper `<maintenanceevent>` to provide the according context.

@alexduryee - please let @SJagodzinski know, should you need any further feedback from her for this. Otherwise, we'll leave the integration into the TL to you. Thank you!
