### ISSUE TITLE
EAD3 examples review and cleanup - here: sub-elements of <table>

### ISSUE THREAD

**Issue by kerstarno** [SAA-SDT/EAS-TagLibraries#39]
## Creator of issue

1. Kerstin Arnold
2. TS-EAS EAD team lead
3. @kerstarno

## The issue relates to

- [ ] EAC-CPF schema issue
- [ ] EAC-CPF Tag Library issue
- [ ] EAD schema issue
- [X] EAD Tag Library issue
- [ ] Schema issue
- [ ] Tag Library issue
- [ ] Suggestions for all schemas
- [ ] Suggestions for all Tag Libraries
- [ ] Other

## Wanted change/feature

* Text: Some EAD3 TL elements are missing examples. This issue has been created from #20, where this was initially reported. The current issue deals with the following elements:
- colspec (maybe?)
- tgroup
- thead
- row (maybe?)

**Comment by kerstarno** [comment]
Awaiting confirmation for Caitlin to join before assigning this issue to her.

**Comment by alexduryee** [comment]
Potentially reuse the `entry` table example, which contains `colspec`/`row`

**Comment by CaitlinRizzo** [comment]
@kerstarno Here are suggested examples for colspec, tgroup, thead, and row.

**Example for <colspec>, <tgroup>, and <row> (repurposed from EAD2002 example):** 
  <table frame="none">
        <tgroup cols="3">
            <colspec colnum="1" colname="1" align="left" colwidth="50pt"/>
            <colspec colnum="2" colname="2" align="left" colwidth="50pt"/>
            <colspec colnum="3" colname="3" align="left" colwidth="50pt"/>
            <thead>
                <row>
                    <entry colname="1">Major Family Members</entry>
                    <entry colname="2">Spouses</entry>
                    <entry colname="3">Children</entry>
                </row>
            </thead>
            <tbody>
                <row>
                    <entry colname="1">John Albemarle (1760-1806)</entry>
                    <entry colname="2">Mary Frances Delaney (1769-1835)</entry>
                    <entry colname="3">John Delaney Albemarle (1787-1848)</entry>
                </row> . . .
            </tbody>
        </tgroup>
    </table>

**Example for <thead> (includes <colspec>, <row>, and <tgroup> as well):**
<table frame="all" colsep="true" rowsep="true">
	<head></head>
	<tgroup align="center" cols="3">
		<colspec colname="chaptertitle" colnum="1"/>
		<colspec colname="begindate" colnum="2"/>
		<colspec colname="enddate" colnum="3"/>
		<thead valign="middle">
			<row>
				<entry colname="departmenttitle">Department Title</entry>
				<entry colname="yearformed">Year Formed</entry>
				<entry colname="yeardisbanded">Year Disbanded</entry>
			</row>
		</thead>
		<tbody valign="middle">
			<row>
				<entry colname="chaptertitle">Local Chapter 543</entry>
				<entry colname="yearformed">1923</entry>
				<entry colname="yeardisbanded">1967</entry>
			</row>
		</tbody>
	</tgroup>
</table>
