### ISSUE TITLE
EAD3 tag library specifies that c12 can have thead as a child, even though that element is not valid in a c12

### ISSUE THREAD

**Issue by fordmadox** [SAA-SDT/EAS-TagLibraries#43]
## Creator of issue

1.  Mark Custer

## The issue relates to

- [ ] EAC-CPF schema issue
- [ ] EAC-CPF Tag Library issue
- [ ] EAD schema issue
- [x] EAD Tag Library issue
- [ ] Schema issue
- [ ] Tag Library issue
- [ ] Suggestions for all schemas
- [ ] Suggestions for all Tag Libraries
- [ ] Other

## Wanted change/feature

* Text: 

## Reporting a bug

* Text:
See https://www.loc.gov/ead/EAD3taglib/index.html#elem-c12  "thead" is listed as an available child element.  The EAD2002 tag library has it right, though:  https://www.loc.gov/ead/tglib/elements/c12.html

## Suggested Solution

* Text: 
Remove "thead" from https://github.com/SAA-SDT/EAS-TagLibraries/blob/master/tei/EAD3-TL-eng.xml#L4110

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Context

* Text: 

## Your Environment can be a clue to a bug

* Version used:
* Environment name and version (e.g. Chrome 39, node.js 5.4):
* Operating System and version (desktop or mobile):

**Comment by kerstarno** [comment]
During their meeting on 28 October, EAD team of TS-EAS briefly discussed this issue as being a minor bug fix for the TL, which should be taken care of in the context of other updates to the TL (see e.g. #37 and #38).
