### ISSUE TITLE
Add <rightsdeclaration> to summary of <citation> in EAD3 TL

### ISSUE THREAD

**Issue by kerstarno** [SAA-SDT/EAS-TagLibraries#47]
## Creator of issue

1. Kerstin Arnold
2. here: TS-EAS member / lead of EAD team
3. @kerstarno 
4.

## The issue relates to

- [ ] EAC-CPF schema issue
- [ ] EAC-CPF Tag Library issue
- [ ] EAD schema issue
- [x] EAD Tag Library issue
- [ ] Schema issue
- [ ] Tag Library issue
- [ ] Suggestions for all schemas
- [ ] Suggestions for all Tag Libraries
- [ ] Other

## Wanted change/feature

* Text: 

## Reporting a bug

* Text: The summary of `<citation>` in the EAD3 tag library lists the parent elements `<conventiondeclaration>` and `<localtypedeclaration>`, but misses the new `<rightsdeclaration>`. This only refers to the "Summary". (And it's correct in EAC-CPF TL, i.e. has only slipped through in EAD3 TL it seems.)

## Suggested Solution

* Text: 

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Context

* Text: 

## Your Environment can be a clue to a bug

* Version used:
* Environment name and version (e.g. Chrome 39, node.js 5.4):
* Operating System and version (desktop or mobile):

**Comment by kerstarno** [comment]
@alexduryee - not sure, if we can sneak this into the EAD3 1.1.1 patch?

**Comment by fordmadox** [comment]
@kerstarno just a note that it looks like @alexduryee has already fixed this.  see https://github.com/SAA-SDT/EAS-TagLibraries/blob/ad/examples_update/tei/EAD3-TL-eng.xml#L4580.  so, once we get the new files up on the LoC website, things should be good, I think.  i'll create a new v1.1.1 branch just to make sure that i've got all of the updates requested in one place.
