### ISSUE TITLE
<c> element (unnumbered and all numbered variations) don't have an element name in the TL

### ISSUE THREAD

**Issue by kerstarno** [SAA-SDT/EAS-TagLibraries#49]
## Creator of issue

1. Kerstin Arnold
2. TS-EAS member
3. @kerstarno 
4.

## The issue relates to

- [ ] EAC-CPF schema issue
- [ ] EAC-CPF Tag Library issue
- [ ] EAD schema issue
- [x] EAD Tag Library issue
- [ ] Schema issue
- [ ] Tag Library issue
- [ ] Suggestions for all schemas
- [ ] Suggestions for all Tag Libraries
- [ ] Other

## Wanted change/feature

* Text: 

## Reporting a bug

* Text: Neither the unnumber element `<c>` nor any of the numbered versions (from `<c01>` to `<c12>` have an element name in the tag library. There is only the tag name displayed along with the link to the table of contents. This is the case for the HTML and the PDF version of the tag library alike. Not sure, if this always has been missing as e.g. the comparison table from 2018 also doesn't list an element name for these, but only the tag name. 
This might mainly be a display issue, as the linking (i.e. using the URL https://www.loc.gov/ead/EAD3taglib/EAD3.html#elem-c, for example, to get to the description of `<c>`) seems to work fine.

## Suggested Solution

* Text: The EAD 2002 tag library does include element names. These should be added here accordingly, i.e. "Component (unnumbered)" for `<c>` and "Component (first level)" for `<c01>`, "Component (second level)" for `<c02>` etc.

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Context

* Text: 

## Your Environment can be a clue to a bug

* Version used: latest version EAD3 1.1.1
* Environment name and version (e.g. Chrome 39, node.js 5.4): on Firefox (latest version)
* Operating System and version (desktop or mobile): with MAC

**Comment by kerstarno** [comment]
@alexduryee - while I can see the changes having been made (https://github.com/SAA-SDT/EAS-TagLibraries/pull/72/files), the draft PDF still only shows the element tags, but not the element names as the headers for these sections.

**Comment by alexduryee** [comment]
Fixed on development branch.
