### ISSUE TITLE
bioghist ISAD(G) Tag Library Error

### ISSUE THREAD

**Issue by ruthtillman** [SAA-SDT/EAS-TagLibraries#5]
Opening ticket on behalf of email reporter (email to LOC):

## Creator of issue

1. Melissa Nerino
2. Associate Archivist
3. Industrial Archives
4.

## The issue relates to

- [ ] EAC-CPF schema issue
- [ ] EAC-CPF Tag Library issue
- [ ] EAD schema issue
- [X ] EAD Tag Library issue
- [ ] Schema issue
- [ ] Tag Library issue
- [ ] Suggestions for all schemas
- [ ] Suggestions for all Tag Libraries
- [ ] Other

## Wanted change/feature

* Text:  On the EAD3 Tag Library site<https://www.loc.gov/ead/EAD3taglib/index.html>, the tag <bioghist> references ISAD(G) 3.2.1 (Name of creator) . However, it should refer to ISAD(G) 3.2.2 (Administrative/Biographical history).

**Comment by alexduryee** [comment]
Fixed in the 1.1 release of the EAD3 TL - thanks!
