### ISSUE TITLE
rightsdeclaration is missing for <abbr>

### ISSUE THREAD

**Issue by SJagodzinski** [SAA-SDT/EAS-TagLibraries#53]
`<abbr>`: the list _May occur within_ is missing the element `<rightsdeclaration>`.

## Creator of issue
1. Silke Jagodzinski

## The issue relates to

- [ ] EAC-CPF schema issue
- [ ] EAC-CPF Tag Library issue
- [ ] EAD schema issue
- [x] EAD Tag Library issue
- [ ] Schema issue
- [ ] Tag Library issue
- [ ] Suggestions for all schemas
- [ ] Suggestions for all Tag Libraries
- [ ] Other

## Reporting a bug
[`<abbr>`](https://www.loc.gov/ead/EAD3taglib/EAD3.html#elem-abbr): the list _May occur within_ is missing the element <rightsdeclaration>.

**Comment by kerstarno** [comment]
@alexduryee - while I can see the change having been made in the TEI file (https://github.com/SAA-SDT/EAS-TagLibraries/commit/c9c38aba629c1d1a127ba15ba3868c33a2660ea1), the draft PDF of the TL does not show `<rightsdeclaration>` among the elements that `<abbr>` may occur within.

**Comment by kerstarno** [comment]
@alexduryee - follow-up from the last EAD team meeting to adapt the wording for "Availability" in the description of `<abbr>` within the TL. The first line should say: "Within `<control>`: Optional, not repeatable" rather than only "Within `<conventiondeclaration>`: Optional, not repeatable".
