### ISSUE TITLE
lastdatetimeverified is listed for <sources>

### ISSUE THREAD

**Issue by SJagodzinski** [SAA-SDT/EAS-TagLibraries#54]
`<sources>:` the attribute `@lastdatetimeverified` ist listed as attribute but not available in schema.

## Creator of issue
1. Silke Jagodzinski
2. TS-EAS: EAC-CPF subgroup
3. silkejagodzinski@gmail.com

## The issue relates to

- [ ] EAC-CPF schema issue
- [ ] EAC-CPF Tag Library issue
- [ ] EAD schema issue
- [x] EAD Tag Library issue
- [ ] Schema issue
- [ ] Tag Library issue
- [ ] Suggestions for all schemas
- [ ] Suggestions for all Tag Libraries
- [ ] Other

## Reporting a bug
`<sources>:` the attribute `@lastdatetimeverified` ist listed as attribute but not available in schema.

**Comment by kerstarno** [comment]
@alexduryee - I can see `@lastdatetimeverified` having been removed in the TEI (https://github.com/SAA-SDT/EAS-TagLibraries/pull/72/commits/4aa121687de9297e55dc3bd1b48d0b1defc2c956), but it still shows in the draft PDF for the TL.

**Comment by alexduryee** [comment]
Fixed on development branch.

**Comment by kerstarno** [comment]
Closing this as it has been resolved.
