### ISSUE TITLE
label for @mark

### ISSUE THREAD

**Issue by SJagodzinski** [SAA-SDT/EAS-TagLibraries#55]
Summary label for attribute `@mark` is missing

## Creator of issue
1. Silke Jagodzinski
2. TS-EAS: EAC-CPF subgroup
3. silkejagodzinski@gmail.com

## The issue relates to

- [ ] EAC-CPF schema issue
- [ ] EAC-CPF Tag Library issue
- [ ] EAD schema issue
- [x] EAD Tag Library issue
- [ ] Schema issue
- [ ] Tag Library issue
- [ ] Suggestions for all schemas
- [ ] Suggestions for all Tag Libraries
- [ ] Other

## Wanted change/feature
Change label _Value_ into label _Summary._

## Steps to Reproduce (for bugs)
https://www.loc.gov/ead/EAD3taglib/EAD3.html#attr-mark

## Your Environment can be a clue to a bug

**Comment by kerstarno** [comment]
@alexduryee - while I can see the change from `<div type="values">` to `<div type="summary">` having been made in the TEI file (https://github.com/SAA-SDT/EAS-TagLibraries/pull/72/files), the draft PDF still shows the label "Values" doubled.

**Comment by alexduryee** [comment]
Fixed on development branch.

**Comment by kerstarno** [comment]
Closing this as it has been resolved.
