### ISSUE TITLE
availability missing for <representation>

### ISSUE THREAD

**Issue by SJagodzinski** [SAA-SDT/EAS-TagLibraries#56]
`<representation>`: availability information is missing

## Creator of issue
1. Silke Jagodzinski

## The issue relates to

- [ ] EAC-CPF schema issue
- [ ] EAC-CPF Tag Library issue
- [ ] EAD schema issue
- [x] EAD Tag Library issue
- [ ] Schema issue
- [ ] Tag Library issue
- [ ] Suggestions for all schemas
- [ ] Suggestions for all Tag Libraries
- [ ] Other

## Reporting a bug
[`<representation>`](https://www.loc.gov/ead/EAD3taglib/EAD3.html#elem-representation): availability information is missing

**Comment by kerstarno** [comment]
@alexduryee - while I can see the change having been made in https://github.com/SAA-SDT/EAS-TagLibraries/pull/72/commits/338d1f70f2d7b6a3d74f83894f75a600c16b5817, the section "Availability" does not show in the draft PDF of the TL.

**Comment by alexduryee** [comment]
Fixed on development branch.

**Comment by kerstarno** [comment]
Closing this as it has been resolved.
