### ISSUE TITLE
"Technical" description of availability

### ISSUE THREAD

**Issue by karinbredenberg** [SAA-SDT/EAS-TagLibraries#57]
## Creator of issue

1. Karin Bredenberg, TS EAS co-chair

## The issue relates to

- [ ] EAC-CPF schema issue
- [ ] EAC-CPF Tag Library issue
- [ ] EAD schema issue
- [ ] EAD Tag Library issue
- [ ] Schema issue
- [x] Tag Library issue
- [ ] Suggestions for all schemas
- [ ] Suggestions for all Tag Libraries
- [ ] Other

## Wanted change/feature

* Text: In the "Availability" text add in the end the technical way of giving availability (0..1) and so on. Programmatically in the transformation.

**Comment by ailie-s** [comment]
Draft example of usage for EAC-CPF Tag Library:

`<head>`
	`<gi>nameEntry</gi>`
`</head>`
`<div type="fullName">`
	`<p>Name Entry</p>`
`</div>`
`<div type="summary">`
	`<p>An element containing a name entry for a corporate body, person, or family.</p>`
`</div>`
`<div type="mayContain">`
	**`<p>part (1..n), useDates (0..1)</p>`**
`</div>`
`<div type="mayOccurWithin">`
	`<p>identity, nameEntrySet</p>`
`</div>`

**Comment by alexduryee** [comment]
Just verifying - will this require any changes to the XSLT for TEI->HTML/PDF, or will this be strictly just content changes to the TEI?

**Comment by ailie-s** [comment]
If possible, this will require changes to the XSLT to handle the 'or' cases, eg:

<div type="mayContain">
<p>date or dateRange or dateSet (0..1), descriptiveNote (0..1), placeName (0..n), reference (0..1), term (1..n)</p>
</div>

I've been testing the HTML today - it is handling the availability for individual elements, but it's not working for the 'or' elements. 

I'll have draft of the v2.0 tag library - with the availability information - in GitHub in the next day or so.

**Comment by alexduryee** [comment]
Addressed in #79
