### ISSUE TITLE
Headers Description and Usage needs to be possible to split into two seperate sections

### ISSUE THREAD

**Issue by karinbredenberg** [SAA-SDT/EAS-TagLibraries#58]
## Creator of issue

1. Karin Bredenberg, TS EAS co-chair

## The issue relates to

- [ ] EAC-CPF schema issue
- [ ] EAC-CPF Tag Library issue
- [ ] EAD schema issue
- [ ] EAD Tag Library issue
- [ ] Schema issue
- [x] Tag Library issue
- [ ] Suggestions for all schemas
- [ ] Suggestions for all Tag Libraries
- [ ] Other

## Wanted change/feature

* Text: Make sure its possible to splitt "Description and usage" into to own sections again. Could should be at place just make sure it works.

**Comment by alexduryee** [comment]
Addressed in #79
