### ISSUE TITLE
Addition of italic and bold for text formatting

### ISSUE THREAD

**Issue by karinbredenberg** [SAA-SDT/EAS-TagLibraries#65]
## Creator of issue

1. Karin Bredenberg, TS EAS co-chair

## The issue relates to

- [ ] EAC-CPF schema issue
- [ ] EAC-CPF Tag Library issue
- [ ] EAD schema issue
- [ ] EAD Tag Library issue
- [ ] Schema issue
- [x] Tag Library issue
- [ ] Suggestions for all schemas
- [ ] Suggestions for all Tag Libraries
- [ ] Other

## Wanted change/feature

* Text: Add possibility of gormatting the text with bold and italic. Needs addition in the TEI-schema, template, the two transformations and the template.

**Comment by alexduryee** [comment]
Addressed in PR #79
