### ISSUE TITLE
EAD3 Tag Library indexentry example

### ISSUE THREAD

**Issue by karinbredenberg** [SAA-SDT/EAS-TagLibraries#69]
## Creator of issue

1. Emma Esperon, Library of Congress, eesp@loc.gov

## The issue relates to

- [ ] EAC-CPF schema issue
- [ ] EAC-CPF Tag Library issue
- [ ] EAD schema issue
- [X] EAD Tag Library issue
- [ ] Schema issue
- [ ] Tag Library issue
- [ ] Suggestions for all schemas
- [ ] Suggestions for all Tag Libraries
- [ ] Other

## Wanted change/feature

* Text: My friend Emma Esperon caught a typo in the EAD3 Tag Library (below):

I was browsing indexentry and noticed a stray angle bracket.  Not a deal 
breaker, just not a great example of good code.

<index>
<indexentry>
<name>
<part>12th Air Force Photo</part>
</name>
<ref target="LOT13105" actuate="onrequest" show="replace">>LOT 13105</ref>
</indexentry>
<indexentry>
<name>
<part>15th Air Force Command:</part>
</name>
<ref target="LOT13105" actuate="onrequest" show="replace">LOT 13105</ref>
</indexentry>
</index>

## Reporting a bug

* Text:

## Suggested Solution

* Text: Delete the extra angle bracket in the html and PDF 
version and all will be good!  When they're updated, let Glenn Gardner know 
at LC and we'll update the EAD site.  Thanks!

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Context

* Text: 

## Your Environment can be a clue to a bug

* Version used:
* Environment name and version (e.g. Chrome 39, node.js 5.4):
* Operating System and version (desktop or mobile):

**Comment by kerstarno** [comment]
@alexduryee - while I can see the change having been made in https://github.com/SAA-SDT/EAS-TagLibraries/pull/72/files, the stray angle bracket still shows in the PDF. 

It's the first `<indexentry>` example for both `<index>` and `<indexentry>`:

```
<indexentry>
  <name>
    <part>12th Air Force Photo</part>
  </name>
  <ref target="LOT13105" actuate="onrequest" show="replace">>LOT 13105</ref>
</indexentry>
```
