### ISSUE TITLE
EAD2002 tag library HTML display issue

### ISSUE THREAD

**Issue by fordmadox** [SAA-SDT/EAS-TagLibraries#70]
Not much of an issue, but just a note that this page, https://www.loc.gov/ead/tglib/elements/eadgrp.html, is lacking a link to the CSS file.

## Creator of issue

1. Mark Custer, Beinecke Library
2.
3.
4.

## The issue relates to

- [ ] EAC-CPF schema issue
- [ ] EAC-CPF Tag Library issue
- [ ] EAD schema issue
- [ ] EAD Tag Library issue
- [ ] Schema issue
- [ ] Tag Library issue
- [ ] Suggestions for all schemas
- [ ] Suggestions for all Tag Libraries
- [ x ] Other

## Wanted change/feature

* Text: 

## Reporting a bug

* Text:

## Suggested Solution

* Text: 

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Context

* Text: 

## Your Environment can be a clue to a bug

* Version used:
* Environment name and version (e.g. Chrome 39, node.js 5.4):
* Operating System and version (desktop or mobile):

**Comment by alexduryee** [comment]
During 2020-06-08 meeting, subteam discussed and concluded that LC, not TS-EAS, is responsible for managing the page.  Subteam will contact LC regarding fixing the page's CSS.

**Comment by kerstarno** [comment]
Contact with LoC was made and it seems this issue has been around for a while. Glenn's working on getting the page into the new template.

**Comment by kerstarno** [comment]
Issue has now been fixed by LoC.
