### ISSUE TITLE
Update EAC-CPF examples to EAD3

### ISSUE THREAD

**Issue by alexduryee** [SAA-SDT/EAS-TagLibraries#74]
Currently, the EAC-CPF tag library uses examples from EAD in EAD2002.  In addition to using an older standard, this creates difficulties when generating tag library documents.  These examples should be revised to use EAD3 (and the proper namespace).

**Comment by kerstarno** [comment]
Would this be a task for the EAC or the EAD team?

**Comment by alexduryee** [comment]
Good question - I'd say EAC broadly, since the examples/namespaces to update are in that document, and it's something to watch out for during revisions to the TL.  For the current version of the TL, though, it's a small enough update (3 objectxmlwrap examples) that I don't think it necessarily needs to be formalized.

If @ailie-s is okay with me updating the EAC-CPF TEI, I can update the 3 examples now as part of streamlining the PDF/HTML generation process.

**Comment by fordmadox** [comment]
That sounds good to me, @alexduryee .  If I can help, just let me know.

**Comment by ailie-s** [comment]
Most examples were updated for EAC-CPF v2 Tag Library. I cannot find any EAD examples in the current Tag Library.

**Comment by marieelia** [comment]
I believe we can close this as an issue now, but please let me know if there are remaining concerns.
