### ISSUE TITLE
'Attribute Usage' and 'See Also' sections not appearing in PDF Tag Libraries

### ISSUE THREAD

**Issue by ailie-s** [SAA-SDT/EAS-TagLibraries#81]
The 'Attribute Usage' and 'See Also' sections of element descriptions are not appearing in PDF Tag Libraries.

## Creator of issue

1. Ailie Smith
2. The University of Melbourne
3.
4.

## The issue relates to

- [ ] EAC-CPF schema issue
- [x] EAC-CPF Tag Library issue
- [ ] EAD schema issue
- [x] EAD Tag Library issue
- [ ] Schema issue
- [x] Tag Library issue
- [ ] Suggestions for all schemas
- [ ] Suggestions for all Tag Libraries
- [ ] Other

## Wanted change/feature

* Text: 

## Reporting a bug

* Text: After running the build script to create the PDF and HTML Tag Libraries for EAC-CPF, I've discovered that the PDF Tag Library does not include the content from `<div type="attributeusage">` and `<div type="seealso">` in the element descriptions. This means that none of the 'Attribute Usage' or 'See Also' text is appearing in the PDF version of the Tag Library. I checked the current EAD3 Tag Libraries online and the same issue is occurring there. 

## Suggested Solution

* Text: 

## Steps to Reproduce (for bugs)

1. See for example `<abbr>` in the EAD3 Tag Library ([https://www.loc.gov/ead/EAD3taglib/EAD3.html#elem-abbr](https://www.loc.gov/ead/EAD3taglib/EAD3.html#elem-abbr) and [https://www.loc.gov/ead/EAD3taglib/tl_ead3.pdf](https://www.loc.gov/ead/EAD3taglib/tl_ead3.pdf))
2.
3.
4.

## Context

* Text: 

## Your Environment can be a clue to a bug

* Version used:
* Environment name and version (e.g. Chrome 39, node.js 5.4):
* Operating System and version (desktop or mobile):

**Comment by alexduryee** [comment]
The issue is that `attributeusage` and `seealso` use `<list>`, despite being descriptive fields.  From the EAD3 TEI:

`<div type="description">
                  <p>Use <gi>agenttype</gi> and the <att>value</att> to indicate the type of agent responsible for the creation, modification, or deletion of an EAD instance, as captured in <gi>maintenanceevent</gi>. The
                     element should remain empty unless text is necessary to provide a value for <gi>agenttype</gi> in a language other than English.</p>
               </div>
               <div type="attributeusage">
                  <list type="simple">
                     <item>
                        <gi>agenttype</gi> requires use of <att>value</att>, which must be set to "human," "machine," or "unknown," and should correspond to the information recorded in <gi>agent</gi>. For example, if the
                           <gi>agent</gi> is Jane Marshall, the value of <gi>agenttype</gi> should be set to "human." If the <gi>agent</gi> is a database, style sheet, or other system, the value of <gi>agenttype</gi>
                        should be set to "machine." The value of <gi>agenttype</gi> may also be set to "unknown" if the agent and/or type of agent cannot be determined.</item>
                  </list>
               </div>
               <div type="seealso">
                  <list type="simple">
                     <item>Use the sibling element <gi>agent</gi> to encode the agent’s name.</item>
                  </list>
               </div>`

I'm not 100% clear why this is jamming the transformer - lists work in other elements - so it's definitely a tricky one!  It's definitely something that needs to be fixed, though - I've started digging into it.

**Comment by alexduryee** [comment]
Resolved in https://github.com/SAA-SDT/EAS-TagLibraries/pull/80 - just needed to add those fields to the big list of elements (oops) and tweak their display to account for the list contents.

**Comment by ailie-s** [comment]
Thanks @alexduryee  - I have tested the update with the EAC-CPF 2.0 Tag Library and this has resolved the issue.
