### ISSUE TITLE
Typo in EAD3 <relation> example

### ISSUE THREAD

**Issue by alexduryee** [SAA-SDT/EAS-TagLibraries#84]
From the EAD3 tag library for `relation`:
```
<div type="examples">
  <p>See examples under <gi>relation</gi>.</p>
</div>
```

This is circular and should refer to `relations`

**Comment by kerstarno** [comment]
Hi @alexduryee, the HTML and PDF versions of the EAD3 Tag Library have now been updated on the LoC website and while checking them briefly for the changes included in this minor release, I found that - for whatever reason - this change does not display in the HTML TL. It only displays the label "Example", but not the text (which is showing fine in the PDF). It's rows 14438 to 14440 in the TEI XML. Possibly something to do with the HTML transformation?

We probably should create a new issue to look at this, but I'll leave this to you, if I may, as you will know better what this might possibly refer to.
