### ISSUE TITLE
Repeatability for <ref> and <ptr> misleading in EAD3 tag library

### ISSUE THREAD

**Issue by erussey** [SAA-SDT/EAS-TagLibraries#85]
In the EAD3 tag library description for `<ref>`, the availability of the tag is listed as optional and repeatable within all parent elements except `<ptrgrp>`.  This is incorrect for `<indexentry>` (which is listed as one of the elements that `<ref>` can occur within), which requires an intermediate `<ptrgrp>` for multiple `<ref>`.

## Creator of issue

1. Elizabeth Roke
2. Emory University
3. erussey@emory.edu

## The issue relates to

- [ ] EAC-CPF schema issue
- [ ] EAC-CPF Tag Library issue
- [ ] EAD schema issue
- [x] EAD Tag Library issue
- [ ] Schema issue
- [ ] Tag Library issue
- [ ] Suggestions for all schemas
- [ ] Suggestions for all Tag Libraries
- [ ] Other

## Wanted change/feature

* Text: 

## Reporting a bug

* Text:

## Suggested Solution

* Text: 

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Context

* Text: 

## Your Environment can be a clue to a bug

* Version used:
* Environment name and version (e.g. Chrome 39, node.js 5.4):
* Operating System and version (desktop or mobile):

**Comment by kerstarno** [comment]
Well spotted, @erussey - thanks very much. 

`<indexentry>` indeed can either have a single `<ref>` or a single `<ptr>` or it can use `<ptrgrp>` to allow for either of `<ref>` or `<ptr>` to be repeated. The same misleading repeatability statement also is effective for `<ptr>`, by the way. 

@alexduryee - could you please have a look at this and prepare a correction of the "Availability" section for both, `<ref>` and `<ptr>` to state the following:

Within `<ptrgrp>`: One of `<ptr>` or `<ref>` is required, repeatable
Within `<indexentry>`: Optional, not repeatable
Within all other parents: Optional, repeatable

**Comment by alexduryee** [comment]
Fix is live on development - should we close this?
