### ISSUE TITLE
Tag Library: example error in <bibref>

### ISSUE THREAD

**Issue by SJagodzinski** [SAA-SDT/EAS-TagLibraries#86]
There is an error in one of the `<bibref>` examples in the Tag Library.

## Creator of issue

1. Silke Jagodzinski
2. @SJagodzinski 
3.
4.

## The issue relates to

- [ ] EAC-CPF schema issue
- [ ] EAC-CPF Tag Library issue
- [ ] EAD schema issue
- [x] EAD Tag Library issue
- [ ] Schema issue
- [ ] Tag Library issue
- [ ] Suggestions for all schemas
- [ ] Suggestions for all Tag Libraries
- [ ] Other

## Wanted change/feature

* Text: 

## Reporting a bug

* Text:
1st example: `<bibref>` is not a child element of `<p>`

## Suggested Solution

* Text: 

## Steps to Reproduce (for bugs)

1. [https://www.loc.gov/ead/EAD3taglib/EAD3.html#elem-bibref](https://www.loc.gov/ead/EAD3taglib/EAD3.html#elem-bibref)
2.
3.
4.

## Context

* Text: 

## Your Environment can be a clue to a bug

* Version used:
* Environment name and version (e.g. Chrome 39, node.js 5.4):
* Operating System and version (desktop or mobile):

**Comment by kerstarno** [comment]
@alexduryee - here's the encoding example that we discussed just now in the Schema team meeting:

```
<otherfindaid>
  <bibref>The Archibald MacLeish Papers are described in
    <title render="italic">
      <part>Library of Congress Acquisitions: Manuscript Division, 1982</part>
    </title>
  , p. 29. </bibref>
</otherfindaid>
```
