### ISSUE TITLE
Display of examples in PDF Tag Library

### ISSUE THREAD

**Issue by ailie-s** [SAA-SDT/EAS-TagLibraries#87]
Display of examples in PDF Tag Library

## Creator of issue

1. Ailie Smith (@ailie-s )
2.
3.
4.

## The issue relates to

- [ ] EAC-CPF schema issue
- [X] EAC-CPF Tag Library issue
- [ ] EAD schema issue
- [ ] EAD Tag Library issue
- [ ] Schema issue
- [ ] Tag Library issue
- [ ] Suggestions for all schemas
- [X] Suggestions for all Tag Libraries
- [ ] Other

## Wanted change/feature

When there are multiple examples for a single element or attribute, would it be possible to add a line break between the examples? At the moment it is difficult to tell where one example ends and the next starts.

## Reporting a bug

* Text:

## Suggested Solution

* Text: Suggest change at line 1427 of tagLibrary2pdf.xsl
from: `<fo:block font-family="monospace" font-size="10pt">`
to: `<fo:block font-family="monospace" font-size="10pt" space-after="12pt">`

## Steps to Reproduce (for bugs)

1. See for example `<biogHist>` or `<chronItemSet>` in https://github.com/ailie-s/EAS-TagLibraries/blob/master/tei/eac.pdf
2.
3.
4.

## Context

* Text: 

## Your Environment can be a clue to a bug

* Version used:
* Environment name and version (e.g. Chrome 39, node.js 5.4):
* Operating System and version (desktop or mobile):

**Comment by alexduryee** [comment]
Resolved in #92 - thanks @ailie-s !
