### ISSUE TITLE
Display of non-Latin characters in PDF Tag Library

### ISSUE THREAD

**Issue by ailie-s** [SAA-SDT/EAS-TagLibraries#88]
Non-Latin characters are not displaying in the PDF Tag Library

## Creator of issue

1. Ailie Smith (@ailie-s)
2.
3.
4.

## The issue relates to

- [ ] EAC-CPF schema issue
- [X] EAC-CPF Tag Library issue
- [ ] EAD schema issue
- [ ] EAD Tag Library issue
- [ ] Schema issue
- [X] Tag Library issue
- [ ] Suggestions for all schemas
- [ ] Suggestions for all Tag Libraries
- [ ] Other

## Wanted change/feature

* Text: 

## Reporting a bug

* Text: When non-Latin characters have been used in an example in the EAC-CPF PDF tag Library, they are not being displayed. They are displaying in the HTML version of the Tag Library, but in the PDF version they display as:
`<nameEntry languageOfElement="ja"
scriptOfElement="Jpan" preferredForm="false"
status="authorized" localType="translation">
<part localType="surname">#####</part>
<part localType="firstname">##</part>
</nameEntry>`

## Suggested Solution

* Text: 

## Steps to Reproduce (for bugs)

1. See for example `<nameEntrySet>` in https://github.com/ailie-s/EAS-TagLibraries/blob/master/tei/eac.pdf
2.
3.
4.

## Context

* Text: 

## Your Environment can be a clue to a bug

* Version used:
* Environment name and version (e.g. Chrome 39, node.js 5.4):
* Operating System and version (desktop or mobile):

**Comment by alexduryee** [comment]
I added support for Chinese, Japanese, and Korean character sets on https://github.com/SAA-SDT/EAS-TagLibraries/tree/eac-chinese-translation - I tested this against the latest development version of the EAC 2.0 PDF, and it appeared to work properly.
