### ISSUE TITLE
Whitespace between title and edition on page 2 of pdf tag library

### ISSUE THREAD

**Issue by ailie-s** [SAA-SDT/EAS-TagLibraries#90]
There is an additional space appearing between the title and edition on page 2 of the tag library. EG:
Encoded Archival Context - Corporate Bodies, Persons, and Families (EAC-CPF) Tag Library draft Version EAC-CPF 2.0 , 2021 Edition

## Creator of issue
1. Ailie Smith
2. @ailie-s 
3.
4.

## The issue relates to

- [ ] EAC-CPF schema issue
- [ ] EAC-CPF Tag Library issue
- [ ] EAD schema issue
- [ ] EAD Tag Library issue
- [ ] Schema issue
- [x] Tag Library issue
- [ ] Suggestions for all schemas
- [ ] Suggestions for all Tag Libraries
- [ ] Other

## Wanted change/feature

* Text: 

## Reporting a bug

* Text:
* There is an extra space appearing between the title and the edition at the top of page 2 in the pdf versions of both the EAC-CPF v2.0 and EAD3 Tag Libraries. For example, in the EAC-CPF version 2 Tag Library "Encoded Archival Context - Corporate Bodies, Persons, and Families (EAC-CPF) Tag Library draft Version EAC-CPF 2.0 , 2021 Edition"

## Suggested Solution

* Text: 
* I was able to remove the space by removing the line `<xsl:text> </xsl:text>` in the below code from tagLibray2pdf.xsl file, however this also removed the space between the main and additional titles.
`<xsl:template name="secondpage">`
        `<fo:block font-weight="bold" space-after="6pt" padding-before="-50pt">`
            `<xsl:for-each** select="tei:docTitle/tei:titlePart">`
                `<xsl:value-of select="."/>`
                `<xsl:text> </xsl:text>`
            `</xsl:for-each>`
            `<xsl:text>, </xsl:text>`
            `<xsl:value-of select="tei:docEdition"/>`
        `</fo:block>`

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Context

* Text: 

## Your Environment can be a clue to a bug

* Version used:
* Environment name and version (e.g. Chrome 39, node.js 5.4):
* Operating System and version (desktop or mobile):

**Comment by ailie-s** [comment]
Possible solution (appears to work for EAC v2 Tag Library):

`<xsl:template name="secondpage">`
`<fo:block font-weight="bold" space-after="6pt" padding-before="-50pt">`
`<xsl:for-each** select="tei:docTitle/tei:titlePart">`
`<xsl:choose>`
`<xsl:when test="not(position() ne last())">`
`<xsl:value-of select="."/>`
`</xsl:when>`
`<xsl:otherwise>`
`<xsl:value-of select="."/>`
`<xsl:text> </xsl:text>`
`</xsl:otherwise>`
`</xsl:choose>`
`</xsl:for-each>`
`<xsl:text>, </xsl:text>`
`<xsl:value-of select="tei:docEdition"/>`
`</fo:block>`
[...]

**Comment by alexduryee** [comment]
Resolved in #92 - thanks @ailie-s !
